name: Build and release

on:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  universal:
    runs-on: ubuntu-latest
    needs: goreleaser
    steps:
      - name: Log in to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Build and push universal binary
        if: startsWith(github.ref, 'refs/tags/v')
        uses: manojkarthick/macos-universal-binary-action@alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: "manojkarthick"
          repository: "amalgam"
          tag: "latest"
          amd64: "darwin-amd64"
          arm64: "darwin-arm64"
          compressed: "true"
          overwrite: "true"
          universal: "all"
          binary-path: "amalgam"
